server:
  port: 8080

spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://localhost:9090
            predicates:
#              - Cookie=chocolate, ch.p
              - Path=/users/**

          - id: rating-service
            uri: http://localhost:9080
            predicates:
#              - Cookie=chocolate, ch.p
              - Path=/rating/**
        form-filter:
          enabled: true

